development:
  SECRET_KEY: 'E6D5E1G8Q4E69R4CE6D5E1G8Q4E69R4C'
  BASE_URL: 'http://localhost:3000'
  DATABASE_USERNAME: 'alextang'
  DATABASE_PASSWORD: 'Alex@1030'
production:
  SECRET_KEY: ''
  BASE_URL: ''
  DATABASE_USERNAME: 'alextang'
  DATABASE_PASSWORD: 'Alex@1030'
test:
  SECRET_KEY: ''
  BASE_URL: ''
  DATABASE_USERNAME: 
  DATABASE_PASSWORD: 